import type {
  TornTransitionPreset,
  TornTransitionSettings,
} from "./transition-types";

/**
 * Baseline sheet: mid-weight handmade paper with a torn leading edge, moderate
 * bubbling and a warm three-stop gradient. Every preset is expressed as a diff
 * against this so a new preset only has to state what makes it different.
 */
export const DEFAULT_SETTINGS: TornTransitionSettings = {
  // Motion
  direction: "left-right",
  duration: 1150,
  outroDuration: 980,
  easing: "cubic",
  swapMidpoint: 0.88,
  startDelay: 0,
  revealMode: "sweep",
  edgeVelocity: 1,
  overshoot: 0.18,
  settleDuration: 140,
  coveredHold: 110,

  // Shape
  edgeProfile: "torn",
  bandWidth: 0.22,
  tearAmplitude: 0.11,
  tearFrequency: 1.5,
  edgeRoughness: 0.8,
  edgeSharpness: 0.72,
  edgeThickness: 0.16,
  secondaryEdgeOffset: 0.05,
  fragmentAmount: 0.3,
  holeAmount: 0.16,
  directionalStretch: 2.6,
  foldAmount: 0.24,

  // Bubbles
  bubbleAmount: 0.55,
  bubbleScale: 5.5,
  bubbleVariation: 0.7,
  bubbleInflation: 1,
  bubbleMerge: 0.35,
  bubbleSpeed: 0.4,
  bubbleEdgeConcentration: 0.7,
  pointerInfluence: 0.35,

  // Paper
  fiberAmount: 0.5,
  fiberLength: 2.2,
  fiberDirection: 0.35,
  pulpGrain: 0.55,
  speckleAmount: 0.3,
  wrinkleAmount: 0.4,
  wrinkleScale: 2.4,
  paperDensity: 0.5,
  deckleStrength: 0.3,

  // Depth & lighting
  surfaceDepth: 1,
  displacementStrength: 0.85,
  lightX: -0.45,
  lightY: 0.62,
  lightHeight: 0.7,
  diffuseStrength: 1,
  rimStrength: 0.35,
  specularStrength: 0.25,
  roughness: 0.72,
  cavityShadow: 0.45,
  castShadowStrength: 0.5,
  edgeHighlight: 0.4,
  undersideDarkness: 0.5,

  // Gradient
  paletteMode: "stops",
  cosinePalette: "aurora",
  stopCount: 3,
  color1: "#f4ede4",
  color2: "#d8c7bb",
  color3: "#9aa3b2",
  color4: "#2c2f36",
  gradientAngle: 0.5,
  gradientScale: 0.9,
  gradientMotion: 0.3,
  hueTravel: 0.12,
  saturation: 1,
  brightness: 1,
  contrast: 1,
  colorDistortion: 0.4,
  iridescence: 0.25,

  // Texture & finishing
  grain: 0.12,
  dither: 0.6,
  blur: 0,
  edgeGlow: 0.15,
  chromaticSeparation: 0.12,
  vignette: 0.15,
  alpha: 1,
  textureScale: 1,
  animationSpeed: 1,
};

function preset(
  id: string,
  name: string,
  description: string,
  swatch: [string, string],
  overrides: Partial<TornTransitionSettings>,
): TornTransitionPreset {
  return {
    id,
    name,
    description,
    swatch,
    settings: { ...DEFAULT_SETTINGS, ...overrides },
  };
}

export const TRANSITION_PRESETS: TornTransitionPreset[] = [
  preset(
    "soft-pulp",
    "Soft Pulp",
    "Warm off-white cotton rag. Wide feathered tear, slow rounded bubbles, gentle raking light.",
    ["#f6f1ea", "#d9c4bd"],
    {
      edgeProfile: "soft",
      bandWidth: 0.32,
      tearAmplitude: 0.095,
      tearFrequency: 1.15,
      edgeRoughness: 0.55,
      edgeSharpness: 0.42,
      edgeThickness: 0.2,
      fragmentAmount: 0.16,
      holeAmount: 0.06,
      foldAmount: 0.3,
      bubbleAmount: 0.62,
      bubbleScale: 4.2,
      bubbleInflation: 1.15,
      bubbleMerge: 0.55,
      bubbleSpeed: 0.28,
      pulpGrain: 0.72,
      fiberAmount: 0.42,
      wrinkleAmount: 0.5,
      deckleStrength: 0.42,
      surfaceDepth: 1.1,
      roughness: 0.86,
      specularStrength: 0.14,
      rimStrength: 0.3,
      cavityShadow: 0.5,
      castShadowStrength: 0.55,
      undersideDarkness: 0.42,
      stopCount: 4,
      color1: "#faf5ef",
      color2: "#ece0d4",
      color3: "#dcc3bc",
      color4: "#b9b3ad",
      gradientAngle: 0.42,
      gradientScale: 0.72,
      saturation: 0.86,
      iridescence: 0.1,
      chromaticSeparation: 0.06,
      grain: 0.16,
      vignette: 0.2,
      duration: 1280,
      outroDuration: 1080,
    },
  ),
  preset(
    "iridescent-tear",
    "Iridescent Tear",
    "Violet, blue and silver film with a sharp fibrous rip and strong view-dependent sheen.",
    ["#8b6cf0", "#c9cfe8"],
    {
      edgeProfile: "torn",
      bandWidth: 0.2,
      tearAmplitude: 0.125,
      tearFrequency: 1.9,
      edgeRoughness: 0.9,
      edgeSharpness: 0.82,
      edgeThickness: 0.14,
      secondaryEdgeOffset: 0.07,
      fragmentAmount: 0.38,
      holeAmount: 0.2,
      bubbleAmount: 0.48,
      bubbleScale: 6.4,
      bubbleVariation: 0.82,
      bubbleMerge: 0.28,
      fiberAmount: 0.38,
      pulpGrain: 0.34,
      speckleAmount: 0.18,
      surfaceDepth: 1.25,
      displacementStrength: 1,
      roughness: 0.36,
      specularStrength: 0.62,
      rimStrength: 0.62,
      edgeHighlight: 0.58,
      stopCount: 4,
      color1: "#6d4cf2",
      color2: "#4f74e3",
      color3: "#b9c6ea",
      color4: "#f4f6ff",
      gradientAngle: 0.9,
      gradientScale: 1.05,
      gradientMotion: 0.45,
      hueTravel: 0.22,
      colorDistortion: 0.62,
      iridescence: 0.78,
      chromaticSeparation: 0.24,
      edgeGlow: 0.28,
      grain: 0.08,
      duration: 1040,
      outroDuration: 880,
    },
  ),
  preset(
    "carbon-paper",
    "Carbon Paper",
    "Graphite and cold grey with a heavily fibrous edge, strong tooth and controlled specular highlights.",
    ["#0a0a0c", "#6e727c"],
    {
      edgeProfile: "fibrous",
      bandWidth: 0.17,
      tearAmplitude: 0.1,
      tearFrequency: 2.4,
      edgeRoughness: 1.05,
      edgeSharpness: 0.88,
      edgeThickness: 0.11,
      secondaryEdgeOffset: 0.04,
      fragmentAmount: 0.42,
      holeAmount: 0.22,
      directionalStretch: 3.4,
      bubbleAmount: 0.3,
      bubbleScale: 7.2,
      bubbleInflation: 0.75,
      bubbleEdgeConcentration: 0.85,
      fiberAmount: 0.95,
      fiberLength: 3.1,
      pulpGrain: 0.78,
      speckleAmount: 0.46,
      wrinkleAmount: 0.32,
      paperDensity: 0.62,
      deckleStrength: 0.24,
      surfaceDepth: 0.9,
      roughness: 0.6,
      specularStrength: 0.42,
      rimStrength: 0.5,
      cavityShadow: 0.68,
      edgeHighlight: 0.82,
      undersideDarkness: 0.72,
      castShadowStrength: 0.7,
      paletteMode: "stops",
      stopCount: 4,
      color1: "#08080a",
      color2: "#1b1c20",
      color3: "#3a3d44",
      color4: "#787d88",
      gradientAngle: 0.2,
      gradientScale: 1.15,
      contrast: 1.14,
      saturation: 0.5,
      iridescence: 0.06,
      chromaticSeparation: 0.05,
      grain: 0.22,
      vignette: 0.26,
      duration: 980,
      outroDuration: 840,
    },
  ),
  preset(
    "inflated-gradient",
    "Inflated Gradient",
    "Thick cyan-to-violet foam. Large merged bubbles, deep displacement, smooth surface tension.",
    ["#22d3ee", "#a855f7"],
    {
      edgeProfile: "bubbled",
      bandWidth: 0.3,
      tearAmplitude: 0.1,
      tearFrequency: 1.05,
      edgeRoughness: 0.5,
      edgeSharpness: 0.55,
      edgeThickness: 0.28,
      fragmentAmount: 0.14,
      holeAmount: 0.08,
      foldAmount: 0.12,
      bubbleAmount: 0.95,
      bubbleScale: 3.1,
      bubbleVariation: 0.6,
      bubbleInflation: 1.55,
      bubbleMerge: 0.72,
      bubbleSpeed: 0.55,
      bubbleEdgeConcentration: 0.5,
      pointerInfluence: 0.6,
      fiberAmount: 0.18,
      pulpGrain: 0.24,
      speckleAmount: 0.1,
      wrinkleAmount: 0.18,
      deckleStrength: 0.12,
      surfaceDepth: 1.9,
      displacementStrength: 1.15,
      roughness: 0.42,
      specularStrength: 0.55,
      rimStrength: 0.48,
      cavityShadow: 0.55,
      edgeHighlight: 0.34,
      undersideDarkness: 0.4,
      stopCount: 3,
      color1: "#22d3ee",
      color2: "#6366f1",
      color3: "#a855f7",
      color4: "#f0abfc",
      gradientAngle: 1.15,
      gradientScale: 0.8,
      gradientMotion: 0.42,
      colorDistortion: 0.85,
      iridescence: 0.4,
      chromaticSeparation: 0.16,
      grain: 0.07,
      duration: 1220,
      outroDuration: 1020,
    },
  ),
  preset(
    "deckled-white",
    "Deckled White",
    "Near-monochrome cotton sheet. Visible pulp, ragged deckled lip, deep cavity shadows, almost no hue.",
    ["#ffffff", "#c9c7c2"],
    {
      edgeProfile: "aggressive",
      bandWidth: 0.19,
      tearAmplitude: 0.145,
      tearFrequency: 1.75,
      edgeRoughness: 1.1,
      edgeSharpness: 0.8,
      edgeThickness: 0.24,
      secondaryEdgeOffset: 0.08,
      fragmentAmount: 0.5,
      holeAmount: 0.26,
      foldAmount: 0.34,
      bubbleAmount: 0.34,
      bubbleScale: 6.8,
      bubbleVariation: 0.85,
      bubbleInflation: 0.85,
      bubbleMerge: 0.24,
      fiberAmount: 0.85,
      fiberLength: 1.6,
      pulpGrain: 0.95,
      speckleAmount: 0.52,
      wrinkleAmount: 0.62,
      wrinkleScale: 3.1,
      paperDensity: 0.72,
      deckleStrength: 0.85,
      surfaceDepth: 1.35,
      displacementStrength: 1.05,
      roughness: 0.9,
      specularStrength: 0.12,
      rimStrength: 0.28,
      cavityShadow: 0.78,
      castShadowStrength: 0.75,
      edgeHighlight: 0.5,
      undersideDarkness: 0.62,
      paletteMode: "mono",
      color1: "#ffffff",
      color2: "#cfccc6",
      gradientAngle: 0.3,
      gradientScale: 0.6,
      gradientMotion: 0.12,
      hueTravel: 0,
      saturation: 0.18,
      contrast: 1.08,
      colorDistortion: 0.55,
      iridescence: 0.05,
      chromaticSeparation: 0.03,
      grain: 0.2,
      vignette: 0.24,
      duration: 1100,
      outroDuration: 920,
    },
  ),
  preset(
    "electric-fiber",
    "Electric Fiber",
    "Black stock shot through with orange, magenta and ultraviolet fibres that light up along the rip.",
    ["#0a0810", "#ff1f6b"],
    {
      edgeProfile: "fibrous",
      bandWidth: 0.16,
      tearAmplitude: 0.13,
      tearFrequency: 2.6,
      edgeRoughness: 1.15,
      edgeSharpness: 0.9,
      edgeThickness: 0.1,
      secondaryEdgeOffset: 0.06,
      fragmentAmount: 0.55,
      holeAmount: 0.3,
      directionalStretch: 3.8,
      bubbleAmount: 0.36,
      bubbleScale: 7.8,
      bubbleVariation: 0.9,
      bubbleEdgeConcentration: 0.95,
      bubbleSpeed: 0.75,
      fiberAmount: 1.05,
      fiberLength: 3.6,
      fiberDirection: 0.12,
      pulpGrain: 0.4,
      speckleAmount: 0.35,
      paperDensity: 0.45,
      surfaceDepth: 1.05,
      roughness: 0.52,
      specularStrength: 0.5,
      rimStrength: 0.7,
      cavityShadow: 0.72,
      edgeHighlight: 0.95,
      undersideDarkness: 0.8,
      castShadowStrength: 0.65,
      stopCount: 4,
      color1: "#08070a",
      color2: "#ff5a1f",
      color3: "#ff1f6b",
      color4: "#7c3aed",
      gradientAngle: 0.15,
      gradientScale: 1.35,
      gradientMotion: 0.6,
      hueTravel: 0.42,
      contrast: 1.18,
      colorDistortion: 0.95,
      iridescence: 0.32,
      chromaticSeparation: 0.3,
      edgeGlow: 0.62,
      grain: 0.14,
      vignette: 0.3,
      duration: 900,
      outroDuration: 780,
    },
  ),
];

export const DEFAULT_PRESET_ID = "soft-pulp";

export function findPreset(id: string): TornTransitionPreset | undefined {
  return TRANSITION_PRESETS.find((p) => p.id === id);
}

export function presetSettings(id: string): TornTransitionSettings {
  return findPreset(id)?.settings ?? DEFAULT_SETTINGS;
}

/**
 * Ranges the randomiser is allowed to touch, with bounds chosen so every roll
 * still lands on something presentable. Timing, palette and finishing are left
 * alone on purpose — randomising those is where "generative" turns into "ugly".
 */
const RANDOM_RANGES: Partial<
  Record<keyof TornTransitionSettings, [number, number]>
> = {
  bandWidth: [0.15, 0.34],
  tearAmplitude: [0.07, 0.15],
  tearFrequency: [1, 2.6],
  edgeRoughness: [0.5, 1.1],
  edgeSharpness: [0.45, 0.9],
  edgeThickness: [0.1, 0.28],
  secondaryEdgeOffset: [0, 0.08],
  fragmentAmount: [0.12, 0.52],
  holeAmount: [0.05, 0.28],
  directionalStretch: [1.8, 3.8],
  foldAmount: [0.08, 0.36],
  bubbleAmount: [0.3, 0.95],
  bubbleScale: [3, 7.6],
  bubbleVariation: [0.5, 0.9],
  bubbleInflation: [0.8, 1.5],
  bubbleMerge: [0.2, 0.7],
  bubbleEdgeConcentration: [0.45, 0.95],
  fiberAmount: [0.25, 1],
  pulpGrain: [0.25, 0.9],
  wrinkleAmount: [0.15, 0.6],
  deckleStrength: [0.1, 0.7],
  surfaceDepth: [0.85, 1.85],
  lightX: [-0.8, 0.8],
  lightY: [0.25, 0.85],
  rimStrength: [0.25, 0.7],
  specularStrength: [0.12, 0.6],
  roughness: [0.35, 0.9],
  cavityShadow: [0.35, 0.78],
  edgeHighlight: [0.3, 0.9],
  undersideDarkness: [0.35, 0.75],
  gradientAngle: [0, 1.6],
  gradientScale: [0.6, 1.3],
  colorDistortion: [0.3, 0.9],
  iridescence: [0.05, 0.7],
};

/** Rolls the shape/material dials while keeping the current palette and timing. */
export function randomizeSettings(
  base: TornTransitionSettings,
): TornTransitionSettings {
  const next = { ...base };
  for (const [key, range] of Object.entries(RANDOM_RANGES)) {
    if (!range) continue;
    const [min, max] = range;
    const value = min + Math.random() * (max - min);
    (next as Record<string, unknown>)[key] = Number(value.toFixed(3));
  }
  return next;
}
