import { EASE_OPTIONS } from "@/components/text-animations/shared";
import {
  CursorAsciiReveal,
  DirectionalLetterFlip,
  GlideTextAnimation,
  LetterFlipFrame,
  PouredTextAnimation,
  RandomLetterFadeAnimation,
  ScaleAnchorTextAnimation,
  ScrollLineRevealAnimation,
  StrokeFillGlowAnimation,
  TypingAnimation,
} from "@/components/text-animations";
import type { AnimationDefinition, AnimationSettings } from "./types";

export const DEFAULT_PREVIEW_TEXT = "Maser Media";

const textControl = {
  type: "text" as const,
  key: "text",
  label: "Text content",
  group: "content" as const,
};

function easeControl() {
  return {
    type: "select" as const,
    key: "ease",
    label: "Ease",
    group: "timing" as const,
    options: EASE_OPTIONS.map((o) => ({ value: o.value, label: o.label })),
  };
}

export const animationRegistry: AnimationDefinition[] = [
  {
    id: "typing",
    title: "Typing Animation",
    description: "A typing effect where the text appears character by character.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      typingSpeed: 80,
      startDelay: 400,
      showCursor: true,
      cursorBlinkSpeed: 530,
      ease: "ease-out",
      loop: false,
    },
    controls: [
      textControl,
      { type: "slider", key: "typingSpeed", label: "Typing speed (ms)", group: "timing", min: 30, max: 200, step: 5 },
      { type: "slider", key: "startDelay", label: "Start delay (ms)", group: "timing", min: 0, max: 2000, step: 50 },
      { type: "switch", key: "showCursor", label: "Show cursor", group: "style" },
      { type: "slider", key: "cursorBlinkSpeed", label: "Cursor blink (ms)", group: "style", min: 200, max: 1000, step: 10 },
      easeControl(),
      { type: "switch", key: "loop", label: "Loop", group: "timing" },
    ],
    component: TypingAnimation as AnimationDefinition["component"],
  },
  {
    id: "letter-flip-frame",
    title: "Individual Letter Flip Frame",
    description: "Letters individually flip inside the word frame.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      flipSpeed: 600,
      stagger: 60,
      flipAxis: "x",
      perspective: 800,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
      direction: "forward",
    },
    controls: [
      textControl,
      { type: "slider", key: "flipSpeed", label: "Flip speed (ms)", group: "timing", min: 200, max: 1500, step: 50 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 200, step: 5 },
      {
        type: "select",
        key: "flipAxis",
        label: "Flip axis",
        group: "motion",
        options: [
          { value: "x", label: "X" },
          { value: "y", label: "Y" },
          { value: "z", label: "Z" },
        ],
      },
      { type: "slider", key: "perspective", label: "Perspective", group: "motion", min: 300, max: 1500, step: 50 },
      easeControl(),
      {
        type: "select",
        key: "direction",
        label: "Direction",
        group: "motion",
        options: [
          { value: "forward", label: "Forward" },
          { value: "reverse", label: "Reverse" },
        ],
      },
    ],
    component: LetterFlipFrame as AnimationDefinition["component"],
  },
  {
    id: "poured-text",
    title: "Poured Text Curve",
    description: "Text flows into place with a curved motion path.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      speed: 700,
      curveIntensity: 40,
      stagger: 50,
      verticalOffset: -30,
      horizontalOffset: 0,
      blur: 6,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    controls: [
      textControl,
      { type: "slider", key: "speed", label: "Speed (ms)", group: "timing", min: 300, max: 1500, step: 50 },
      { type: "slider", key: "curveIntensity", label: "Curve intensity", group: "motion", min: 0, max: 80, step: 2 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 150, step: 5 },
      { type: "slider", key: "verticalOffset", label: "Vertical offset", group: "motion", min: -80, max: 80, step: 2 },
      { type: "slider", key: "horizontalOffset", label: "Horizontal offset", group: "motion", min: -80, max: 80, step: 2 },
      { type: "slider", key: "blur", label: "Blur", group: "style", min: 0, max: 16, step: 1 },
      easeControl(),
    ],
    component: PouredTextAnimation as AnimationDefinition["component"],
  },
  {
    id: "stroke-fill-glow",
    title: "Stroke to Fill Glow",
    description: "Stroke appears first, fill fades in, then a controlled glow.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      strokeDuration: 800,
      fillDuration: 600,
      glowIntensity: 0.6,
      glowRadius: 12,
      wordStagger: 200,
      strokeWidth: 1.5,
      ease: "ease-out",
    },
    controls: [
      textControl,
      { type: "slider", key: "strokeDuration", label: "Stroke duration (ms)", group: "timing", min: 200, max: 2000, step: 50 },
      { type: "slider", key: "fillDuration", label: "Fill duration (ms)", group: "timing", min: 200, max: 2000, step: 50 },
      { type: "slider", key: "glowIntensity", label: "Glow intensity", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "glowRadius", label: "Glow radius", group: "style", min: 0, max: 32, step: 1 },
      { type: "slider", key: "wordStagger", label: "Word stagger (ms)", group: "timing", min: 0, max: 500, step: 25 },
      { type: "slider", key: "strokeWidth", label: "Stroke width", group: "style", min: 0.5, max: 4, step: 0.25 },
      easeControl(),
    ],
    component: StrokeFillGlowAnimation as AnimationDefinition["component"],
  },
  {
    id: "random-letter-fade",
    title: "Random Letter Fade In",
    description: "Letters fade in individually, optionally in random order.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      fadeSpeed: 500,
      stagger: 40,
      randomOrder: true,
      randomnessAmount: 0.8,
      blur: 4,
      ease: "ease-out",
    },
    controls: [
      textControl,
      { type: "slider", key: "fadeSpeed", label: "Fade speed (ms)", group: "timing", min: 200, max: 1200, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 150, step: 5 },
      { type: "switch", key: "randomOrder", label: "Random order", group: "motion" },
      { type: "slider", key: "randomnessAmount", label: "Randomness amount", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "blur", label: "Blur", group: "style", min: 0, max: 12, step: 1 },
      easeControl(),
    ],
    component: RandomLetterFadeAnimation as AnimationDefinition["component"],
  },
  {
    id: "directional-letter-flip",
    title: "Directional Letter Flip",
    description: "Letters flip into place from a selected direction.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      direction: "top",
      flipSpeed: 550,
      stagger: 45,
      perspective: 900,
      rotationAmount: 90,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    controls: [
      textControl,
      {
        type: "select",
        key: "direction",
        label: "Direction",
        group: "motion",
        options: [
          { value: "top", label: "From top" },
          { value: "bottom", label: "From bottom" },
          { value: "left", label: "From left" },
          { value: "right", label: "From right" },
        ],
      },
      { type: "slider", key: "flipSpeed", label: "Flip speed (ms)", group: "timing", min: 200, max: 1200, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 150, step: 5 },
      { type: "slider", key: "perspective", label: "Perspective", group: "motion", min: 300, max: 1500, step: 50 },
      { type: "slider", key: "rotationAmount", label: "Rotation amount", group: "motion", min: 30, max: 180, step: 5 },
      easeControl(),
    ],
    component: DirectionalLetterFlip as AnimationDefinition["component"],
  },
  {
    id: "cursor-ascii-reveal",
    title: "Cursor ASCII Reveal",
    description: "Interactive ASCII-style reveal driven by cursor hover or touch press.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      revealRadius: 80,
      revealSoftness: 0.5,
      revealSpeed: 0.15,
      asciiDensity: 0.6,
      noiseAmount: 0.4,
      hoverMode: true,
      pressMode: true,
    },
    controls: [
      textControl,
      { type: "slider", key: "revealRadius", label: "Reveal radius", group: "interaction", min: 30, max: 160, step: 5 },
      { type: "slider", key: "revealSoftness", label: "Reveal softness", group: "interaction", min: 0.1, max: 2, step: 0.1 },
      { type: "slider", key: "revealSpeed", label: "Reveal speed", group: "interaction", min: 0.05, max: 0.5, step: 0.01 },
      { type: "slider", key: "asciiDensity", label: "ASCII density", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "noiseAmount", label: "Noise amount", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "switch", key: "hoverMode", label: "Hover mode", group: "interaction" },
      { type: "switch", key: "pressMode", label: "Press mode", group: "interaction" },
    ],
    component: CursorAsciiReveal as AnimationDefinition["component"],
  },
  {
    id: "glide-text",
    title: "Glide Text",
    description: "Words glide onto the screen smoothly from a chosen direction.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      direction: "left",
      glideDistance: 48,
      speed: 650,
      stagger: 120,
      blur: 4,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    controls: [
      textControl,
      {
        type: "select",
        key: "direction",
        label: "Direction",
        group: "motion",
        options: [
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
          { value: "top", label: "Top" },
          { value: "bottom", label: "Bottom" },
          { value: "diagonal", label: "Diagonal" },
        ],
      },
      { type: "slider", key: "glideDistance", label: "Glide distance", group: "motion", min: 12, max: 120, step: 4 },
      { type: "slider", key: "speed", label: "Speed (ms)", group: "timing", min: 300, max: 1500, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 400, step: 10 },
      { type: "slider", key: "blur", label: "Blur", group: "style", min: 0, max: 12, step: 1 },
      easeControl(),
    ],
    component: GlideTextAnimation as AnimationDefinition["component"],
  },
  {
    id: "scale-anchor",
    title: "Scale Anchor Text",
    description: "Words scale from small to full size from a chosen anchor point.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      scaleStart: 0.4,
      scaleEnd: 1,
      speed: 600,
      stagger: 100,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
      anchor: "center",
    },
    controls: [
      textControl,
      { type: "slider", key: "scaleStart", label: "Scale start", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "scaleEnd", label: "Scale end", group: "motion", min: 0.5, max: 1.5, step: 0.05 },
      { type: "slider", key: "speed", label: "Speed (ms)", group: "timing", min: 200, max: 1200, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 300, step: 10 },
      easeControl(),
      {
        type: "select",
        key: "anchor",
        label: "Anchor point",
        group: "motion",
        options: [
          { value: "center", label: "Center" },
          { value: "top", label: "Top" },
          { value: "bottom", label: "Bottom" },
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
          { value: "top-left", label: "Top left" },
          { value: "top-right", label: "Top right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-right", label: "Bottom right" },
        ],
      },
    ],
    component: ScaleAnchorTextAnimation as AnimationDefinition["component"],
  },
  {
    id: "scroll-line-reveal",
    title: "GSAP Scroll Line Reveal",
    description: "Lines of text reveal as the user scrolls. Uses GSAP ScrollTrigger.",
    defaultText: "Maser Media\nScroll to reveal",
    defaultSettings: {
      scrollStart: "top 80%",
      scrollEnd: "top 30%",
      scrubAmount: 1,
      lineStagger: 0.12,
      revealDirection: "up",
      blur: 6,
      opacityFade: true,
      pinSection: false,
    },
    controls: [
      { ...textControl, multiline: true },
      { type: "text", key: "scrollStart", label: "Scroll start", group: "timing" },
      { type: "text", key: "scrollEnd", label: "Scroll end", group: "timing" },
      { type: "slider", key: "scrubAmount", label: "Scrub amount", group: "timing", min: 0, max: 3, step: 0.1 },
      { type: "slider", key: "lineStagger", label: "Line stagger (s)", group: "timing", min: 0, max: 0.5, step: 0.02 },
      {
        type: "select",
        key: "revealDirection",
        label: "Reveal direction",
        group: "motion",
        options: [
          { value: "up", label: "Up" },
          { value: "down", label: "Down" },
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
        ],
      },
      { type: "slider", key: "blur", label: "Blur", group: "style", min: 0, max: 16, step: 1 },
      { type: "switch", key: "opacityFade", label: "Opacity fade", group: "style" },
      { type: "switch", key: "pinSection", label: "Pin section", group: "motion" },
    ],
    dependencies: ["gsap", "@gsap/react"],
    component: ScrollLineRevealAnimation as AnimationDefinition["component"],
  },
];

export function getAnimationById(id: string): AnimationDefinition | undefined {
  return animationRegistry.find((entry) => entry.id === id);
}

export function getDefaultSettings(definition: AnimationDefinition): AnimationSettings {
  return { ...definition.defaultSettings };
}
