import { EASE_OPTIONS } from "@/components/text-animations/shared";
import {
  BlurFocusRevealAnimation,
  CursorAsciiReveal,
  DEFAULT_TETRIS_SETTINGS,
  DirectionalLetterFlip,
  GlyphScanReveal,
  GlideTextAnimation,
  LetterFlipFrame,
  MaskClipRevealAnimation,
  PouredTextAnimation,
  RandomLetterFadeAnimation,
  ScaleAnchorTextAnimation,
  ScrollLineRevealAnimation,
  StrokeFillGlowAnimation,
  TextFlip3DRevealAnimation,
  TextScrambleRevealAnimation,
  TetrisPixelText,
  TypingAnimation,
  UnderlineDrawRevealAnimation,
} from "@/components/text-animations";
import type { AnimationDefinition, AnimationSettings, ControlDefinition } from "./types";

export const DEFAULT_PREVIEW_TEXT = "Maser Media";
const DEFAULT_GLYPH_SVG =
  '<svg viewBox="0 0 160 160" xmlns="http://www.w3.org/2000/svg"><path d="M32 96c18-42 56-64 96-48 20 8 23 34 4 47-22 15-53 5-63-18M36 114c30 20 72 17 96-8" fill="none" stroke="white" stroke-width="20" stroke-linecap="round" stroke-linejoin="round"/></svg>';

const textControl = {
  type: "text" as const,
  key: "text",
  label: "Text content",
  group: "content" as const,
};

function easeControl(): ControlDefinition {
  return {
    type: "select",
    key: "ease",
    label: "Ease",
    group: "timing",
    options: EASE_OPTIONS.map((o) => ({ value: o.value, label: o.label })),
  };
}

function phaseControl(): ControlDefinition {
  return {
    type: "select",
    key: "phase",
    label: "Animation phase",
    group: "motion",
    options: [
      { value: "in", label: "In (entrance)" },
      { value: "out", label: "Out (exit)" },
    ],
  };
}

export const animationRegistry: AnimationDefinition[] = [
  {
    id: "typing",
    title: "Typing Animation",
    description: "A typing effect where the text appears character by character.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      typingSpeed: 80,
      startDelay: 400,
      showCursor: true,
      cursorBlinkSpeed: 530,
      ease: "ease-out",
      loop: false,
    },
    controls: [
      textControl,
      { type: "slider", key: "typingSpeed", label: "Typing speed (ms)", group: "timing", min: 30, max: 200, step: 5 },
      { type: "slider", key: "startDelay", label: "Start delay (ms)", group: "timing", min: 0, max: 2000, step: 50 },
      { type: "switch", key: "showCursor", label: "Show cursor", group: "style" },
      { type: "slider", key: "cursorBlinkSpeed", label: "Cursor blink (ms)", group: "style", min: 200, max: 1000, step: 10 },
      easeControl(),
      { type: "switch", key: "loop", label: "Loop", group: "timing" },
    ],
    supportsOutAnimation: false,
    exportNotes: "Typing is entrance-only. Pair with TextScramble or Glide for exit.",
    component: TypingAnimation as AnimationDefinition["component"],
  },
  {
    id: "letter-flip-frame",
    title: "Individual Letter Flip Frame",
    description: "Letters individually flip inside the word frame.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      flipSpeed: 600,
      stagger: 60,
      flipAxis: "x",
      perspective: 800,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
      direction: "forward",
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "flipSpeed", label: "Flip speed (ms)", group: "timing", min: 200, max: 1500, step: 50 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 200, step: 5 },
      {
        type: "select",
        key: "flipAxis",
        label: "Flip axis",
        group: "motion",
        options: [
          { value: "x", label: "X" },
          { value: "y", label: "Y" },
          { value: "z", label: "Z" },
        ],
      },
      { type: "slider", key: "perspective", label: "Perspective", group: "motion", min: 300, max: 1500, step: 50 },
      easeControl(),
      {
        type: "select",
        key: "direction",
        label: "Direction",
        group: "motion",
        options: [
          { value: "forward", label: "Forward" },
          { value: "reverse", label: "Reverse" },
        ],
      },
    ],
    supportsOutAnimation: true,
    component: LetterFlipFrame as AnimationDefinition["component"],
  },
  {
    id: "poured-text",
    title: "Poured Text Curve",
    description: "Text flows into place with a curved motion path.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      speed: 700,
      curveIntensity: 40,
      stagger: 50,
      verticalOffset: -30,
      horizontalOffset: 0,
      blur: 6,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "speed", label: "Speed (ms)", group: "timing", min: 300, max: 1500, step: 50 },
      { type: "slider", key: "curveIntensity", label: "Curve intensity", group: "motion", min: 0, max: 80, step: 2 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 150, step: 5 },
      { type: "slider", key: "verticalOffset", label: "Vertical offset", group: "motion", min: -80, max: 80, step: 2 },
      { type: "slider", key: "horizontalOffset", label: "Horizontal offset", group: "motion", min: -80, max: 80, step: 2 },
      { type: "slider", key: "blur", label: "Blur", group: "style", min: 0, max: 16, step: 1 },
      easeControl(),
    ],
    supportsOutAnimation: true,
    component: PouredTextAnimation as AnimationDefinition["component"],
  },
  {
    id: "stroke-fill-glow",
    title: "Stroke to Fill Glow",
    description: "Outline strokes in first, fill follows, then a controlled glow.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      strokeDuration: 800,
      fillDuration: 600,
      glowIntensity: 0.6,
      glowRadius: 12,
      wordStagger: 200,
      strokeWidth: 1.5,
      ease: "ease-out",
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "strokeDuration", label: "Stroke duration (ms)", group: "timing", min: 200, max: 2000, step: 50 },
      { type: "slider", key: "fillDuration", label: "Fill duration (ms)", group: "timing", min: 200, max: 2000, step: 50 },
      { type: "slider", key: "glowIntensity", label: "Glow intensity", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "glowRadius", label: "Glow radius", group: "style", min: 0, max: 32, step: 1 },
      { type: "slider", key: "wordStagger", label: "Word stagger (ms)", group: "timing", min: 0, max: 500, step: 25 },
      { type: "slider", key: "strokeWidth", label: "Stroke width", group: "style", min: 0.5, max: 4, step: 0.25 },
      easeControl(),
    ],
    supportsOutAnimation: true,
    component: StrokeFillGlowAnimation as AnimationDefinition["component"],
  },
  {
    id: "random-letter-fade",
    title: "Random Letter Fade In",
    description: "Letters fade in individually, optionally in random order.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      fadeSpeed: 500,
      stagger: 40,
      randomOrder: true,
      randomnessAmount: 0.8,
      blur: 4,
      ease: "ease-out",
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "fadeSpeed", label: "Fade speed (ms)", group: "timing", min: 200, max: 1200, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 150, step: 5 },
      { type: "switch", key: "randomOrder", label: "Random order", group: "motion" },
      { type: "slider", key: "randomnessAmount", label: "Randomness amount", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "blur", label: "Blur", group: "style", min: 0, max: 12, step: 1 },
      easeControl(),
    ],
    supportsOutAnimation: true,
    component: RandomLetterFadeAnimation as AnimationDefinition["component"],
  },
  {
    id: "directional-letter-flip",
    title: "Directional Letter Flip",
    description: "Letters flip into place from a selected direction.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      direction: "top",
      flipSpeed: 550,
      stagger: 45,
      perspective: 900,
      rotationAmount: 90,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    controls: [
      textControl,
      phaseControl(),
      {
        type: "select",
        key: "direction",
        label: "Direction",
        group: "motion",
        options: [
          { value: "top", label: "From top" },
          { value: "bottom", label: "From bottom" },
          { value: "left", label: "From left" },
          { value: "right", label: "From right" },
        ],
      },
      { type: "slider", key: "flipSpeed", label: "Flip speed (ms)", group: "timing", min: 200, max: 1200, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 150, step: 5 },
      { type: "slider", key: "perspective", label: "Perspective", group: "motion", min: 300, max: 1500, step: 50 },
      { type: "slider", key: "rotationAmount", label: "Rotation amount", group: "motion", min: 30, max: 180, step: 5 },
      easeControl(),
    ],
    supportsOutAnimation: true,
    component: DirectionalLetterFlip as AnimationDefinition["component"],
  },
  {
    id: "cursor-ascii-reveal",
    title: "Cursor ASCII Reveal",
    description: "Interactive ASCII-style reveal driven by cursor hover or touch press.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      revealRadius: 80,
      revealSoftness: 0.5,
      revealSpeed: 0.15,
      asciiDensity: 0.6,
      noiseAmount: 0.4,
      hoverMode: true,
      pressMode: true,
    },
    controls: [
      textControl,
      { type: "slider", key: "revealRadius", label: "Reveal radius", group: "interaction", min: 30, max: 160, step: 5 },
      { type: "slider", key: "revealSoftness", label: "Reveal softness", group: "interaction", min: 0.1, max: 2, step: 0.1 },
      { type: "slider", key: "revealSpeed", label: "Reveal speed", group: "interaction", min: 0.05, max: 0.5, step: 0.01 },
      { type: "slider", key: "asciiDensity", label: "ASCII density", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "noiseAmount", label: "Noise amount", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "switch", key: "hoverMode", label: "Hover mode", group: "interaction" },
      { type: "switch", key: "pressMode", label: "Press mode", group: "interaction" },
    ],
    supportsOutAnimation: false,
    exportNotes: "Pointer-driven reveal — no separate out timeline.",
    component: CursorAsciiReveal as AnimationDefinition["component"],
  },
  {
    id: "glyph-scan-reveal",
    title: "Glyph Scan Reveal",
    description: "A scanner reconstructs text or SVG masks from a low-contrast symbol field.",
    defaultText: "Maser",
    defaultSettings: {
      sourceMode: "text",
      svgSource: DEFAULT_GLYPH_SVG,
      cellSize: 14,
      fontFamily: "\"Geist Pixel\", ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace",
      fontWeight: "400",
      foregroundIntensity: 1,
      backgroundDensity: 0.62,
      scanDirection: "left-to-right",
      scanSpeed: 1700,
      decay: 0.68,
      jitter: 0.8,
      symbolSet: "mixed",
    },
    controls: [
      textControl,
      {
        type: "select",
        key: "sourceMode",
        label: "Source mode",
        group: "content",
        options: [
          { value: "text", label: "Text" },
          { value: "svg", label: "SVG / path" },
        ],
      },
      { type: "text", key: "svgSource", label: "SVG source", group: "content", multiline: true },
      { type: "slider", key: "cellSize", label: "Cell size", group: "style", min: 8, max: 24, step: 1 },
      { type: "text", key: "fontFamily", label: "Font family", group: "style" },
      { type: "text", key: "fontWeight", label: "Font weight", group: "style" },
      { type: "slider", key: "foregroundIntensity", label: "Foreground intensity", group: "style", min: 0.2, max: 1.4, step: 0.05 },
      { type: "slider", key: "backgroundDensity", label: "Background density", group: "style", min: 0.1, max: 1, step: 0.05 },
      {
        type: "select",
        key: "scanDirection",
        label: "Scan direction",
        group: "motion",
        options: [
          { value: "left-to-right", label: "Left to right" },
          { value: "right-to-left", label: "Right to left" },
          { value: "top-to-bottom", label: "Top to bottom" },
          { value: "bottom-to-top", label: "Bottom to top" },
        ],
      },
      { type: "slider", key: "scanSpeed", label: "Scan speed (ms)", group: "motion", min: 700, max: 4000, step: 50 },
      { type: "slider", key: "decay", label: "Decay", group: "motion", min: 0.1, max: 1.5, step: 0.05 },
      { type: "slider", key: "jitter", label: "Jitter", group: "motion", min: 0, max: 2, step: 0.1 },
      {
        type: "select",
        key: "symbolSet",
        label: "Symbol set",
        group: "motion",
        options: [
          { value: "mixed", label: "Mixed" },
          { value: "blocks", label: "Blocks" },
          { value: "geometry", label: "Geometry" },
        ],
      },
    ],
    supportsOutAnimation: false,
    exportNotes: "Scan reconstructs once; replay via playKey.",
    component: GlyphScanReveal as AnimationDefinition["component"],
  },
  {
    id: "glide-text",
    title: "Glide Text",
    description: "Words glide onto the screen smoothly from a chosen direction.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      direction: "left",
      glideDistance: 48,
      speed: 650,
      stagger: 120,
      blur: 4,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    controls: [
      textControl,
      phaseControl(),
      {
        type: "select",
        key: "direction",
        label: "Direction",
        group: "motion",
        options: [
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
          { value: "top", label: "Top" },
          { value: "bottom", label: "Bottom" },
          { value: "diagonal", label: "Diagonal" },
        ],
      },
      { type: "slider", key: "glideDistance", label: "Glide distance", group: "motion", min: 12, max: 120, step: 4 },
      { type: "slider", key: "speed", label: "Speed (ms)", group: "timing", min: 300, max: 1500, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 400, step: 10 },
      { type: "slider", key: "blur", label: "Blur", group: "style", min: 0, max: 12, step: 1 },
      easeControl(),
    ],
    supportsOutAnimation: true,
    component: GlideTextAnimation as AnimationDefinition["component"],
  },
  {
    id: "scale-anchor",
    title: "Scale Anchor Text",
    description: "Words scale from small to full size from a chosen anchor point.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      scaleStart: 0.4,
      scaleEnd: 1,
      speed: 600,
      stagger: 100,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
      anchor: "center",
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "scaleStart", label: "Scale start", group: "motion", min: 0.2, max: 1, step: 0.05 },
      { type: "slider", key: "scaleEnd", label: "Scale end", group: "motion", min: 0.5, max: 1.5, step: 0.05 },
      { type: "slider", key: "speed", label: "Speed (ms)", group: "timing", min: 200, max: 1200, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 300, step: 10 },
      easeControl(),
      {
        type: "select",
        key: "anchor",
        label: "Anchor point",
        group: "motion",
        options: [
          { value: "center", label: "Center" },
          { value: "top", label: "Top" },
          { value: "bottom", label: "Bottom" },
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
          { value: "top-left", label: "Top left" },
          { value: "top-right", label: "Top right" },
          { value: "bottom-left", label: "Bottom left" },
          { value: "bottom-right", label: "Bottom right" },
        ],
      },
    ],
    supportsOutAnimation: true,
    component: ScaleAnchorTextAnimation as AnimationDefinition["component"],
  },
  {
    id: "scroll-line-reveal",
    title: "GSAP Scroll Line Reveal",
    description: "Lines of text reveal as the user scrolls. Uses GSAP ScrollTrigger.",
    defaultText: "Maser Media\nScroll to reveal",
    defaultSettings: {
      scrollStart: "top 80%",
      scrollEnd: "top 25%",
      scrubAmount: 1,
      lineStagger: 0.12,
      revealDirection: "up",
      blur: 6,
      opacityFade: true,
      pinSection: false,
    },
    controls: [
      { ...textControl, multiline: true },
      { type: "text", key: "scrollStart", label: "Scroll start", group: "timing" },
      { type: "text", key: "scrollEnd", label: "Scroll end", group: "timing" },
      { type: "slider", key: "scrubAmount", label: "Scrub amount", group: "timing", min: 0, max: 3, step: 0.1 },
      { type: "slider", key: "lineStagger", label: "Line stagger (s)", group: "timing", min: 0, max: 0.5, step: 0.02 },
      {
        type: "select",
        key: "revealDirection",
        label: "Reveal direction",
        group: "motion",
        options: [
          { value: "up", label: "Up" },
          { value: "down", label: "Down" },
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
        ],
      },
      { type: "slider", key: "blur", label: "Blur", group: "style", min: 0, max: 16, step: 1 },
      { type: "switch", key: "opacityFade", label: "Opacity fade", group: "style" },
      { type: "switch", key: "pinSection", label: "Pin section", group: "motion" },
    ],
    dependencies: ["gsap"],
    supportsOutAnimation: false,
    exportNotes: "Scrub is bidirectional — scroll reverse acts as the out animation.",
    component: ScrollLineRevealAnimation as AnimationDefinition["component"],
  },
  {
    id: "mask-clip-reveal",
    title: "Mask Clip Reveal",
    description: "Words rise through an overflow mask — the classic headline reveal.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      speed: 700,
      stagger: 90,
      distance: 110,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "speed", label: "Speed (ms)", group: "timing", min: 300, max: 1400, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 250, step: 5 },
      { type: "slider", key: "distance", label: "Travel distance (%)", group: "motion", min: 40, max: 160, step: 5 },
      easeControl(),
    ],
    supportsOutAnimation: true,
    component: MaskClipRevealAnimation as AnimationDefinition["component"],
  },
  {
    id: "text-scramble-reveal",
    title: "Text Scramble Decode",
    description: "Characters scramble through glyphs then settle — tech / brand decode.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      scrambleSpeed: 28,
      settleDelay: 40,
      cyclesPerChar: 4,
      startDelay: 120,
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "scrambleSpeed", label: "Scramble tick (ms)", group: "timing", min: 12, max: 80, step: 2 },
      { type: "slider", key: "settleDelay", label: "Per-char delay (ms)", group: "timing", min: 10, max: 120, step: 5 },
      { type: "slider", key: "cyclesPerChar", label: "Cycles per char", group: "motion", min: 1, max: 10, step: 1 },
      { type: "slider", key: "startDelay", label: "Start delay (ms)", group: "timing", min: 0, max: 1000, step: 20 },
    ],
    supportsOutAnimation: true,
    component: TextScrambleRevealAnimation as AnimationDefinition["component"],
  },
  {
    id: "blur-focus-reveal",
    title: "Blur Focus Reveal",
    description: "Soft blur and tracking tighten into crisp type.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      speed: 900,
      stagger: 80,
      blurAmount: 16,
      trackingStart: 0.12,
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "speed", label: "Speed (ms)", group: "timing", min: 300, max: 1600, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 200, step: 5 },
      { type: "slider", key: "blurAmount", label: "Blur amount", group: "style", min: 4, max: 32, step: 1 },
      { type: "slider", key: "trackingStart", label: "Start tracking (em)", group: "style", min: 0, max: 0.3, step: 0.01 },
      easeControl(),
    ],
    supportsOutAnimation: true,
    component: BlurFocusRevealAnimation as AnimationDefinition["component"],
  },
  {
    id: "underline-draw-reveal",
    title: "Underline Draw Reveal",
    description: "Words rise while an underline draws under each — CTA treatments.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      speed: 650,
      stagger: 110,
      underlineThickness: 2,
      underlineOffset: 4,
      drawFrom: "left",
      ease: "cubic-bezier(0.22, 1, 0.36, 1)",
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "speed", label: "Speed (ms)", group: "timing", min: 300, max: 1400, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 300, step: 10 },
      { type: "slider", key: "underlineThickness", label: "Underline thickness", group: "style", min: 1, max: 6, step: 0.5 },
      { type: "slider", key: "underlineOffset", label: "Underline offset", group: "style", min: 0, max: 12, step: 1 },
      {
        type: "select",
        key: "drawFrom",
        label: "Draw from",
        group: "motion",
        options: [
          { value: "left", label: "Left" },
          { value: "right", label: "Right" },
          { value: "center", label: "Center" },
        ],
      },
      easeControl(),
    ],
    supportsOutAnimation: true,
    component: UnderlineDrawRevealAnimation as AnimationDefinition["component"],
  },
  {
    id: "text-flip-3d",
    title: "3D Text Flip Reveal",
    description: "Three.js letter planes flip into view with depth — WebGL with CSS fallback.",
    defaultText: DEFAULT_PREVIEW_TEXT,
    defaultSettings: {
      phase: "in",
      flipSpeed: 700,
      stagger: 55,
      flipAxis: "y",
      letterSpacing: 0.12,
      depth: 0.35,
    },
    controls: [
      textControl,
      phaseControl(),
      { type: "slider", key: "flipSpeed", label: "Flip speed (ms)", group: "timing", min: 300, max: 1600, step: 25 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 150, step: 5 },
      {
        type: "select",
        key: "flipAxis",
        label: "Flip axis",
        group: "motion",
        options: [
          { value: "x", label: "X" },
          { value: "y", label: "Y" },
        ],
      },
      { type: "slider", key: "letterSpacing", label: "Letter spacing", group: "style", min: 0, max: 0.4, step: 0.02 },
      { type: "slider", key: "depth", label: "Depth", group: "motion", min: 0, max: 1, step: 0.05 },
    ],
    dependencies: ["three"],
    supportsOutAnimation: true,
    exportNotes: "Requires WebGL. Falls back to CSS 3D flip when unavailable.",
    component: TextFlip3DRevealAnimation as AnimationDefinition["component"],
  },
  {
    id: "tetris-pixel-text",
    title: "Tetris Pixel Text Reveal",
    description:
      "Connected polyomino pieces fall, rotate, and lock into a Geist Pixel word — like Tetris assembling typography.",
    defaultText: "MASER MEDIA",
    defaultSettings: {
      ...DEFAULT_TETRIS_SETTINGS,
      phase: "in",
      paused: false,
    },
    controls: [
      textControl,
      { type: "text", key: "line2", label: "Second line", group: "content" },
      phaseControl(),
      {
        type: "select",
        key: "fontVariant",
        label: "Font variant",
        group: "content",
        options: [
          { value: "geist-pixel-square", label: "Geist Pixel Square" },
          { value: "geist-pixel-grid", label: "Geist Pixel Grid" },
        ],
      },
      { type: "slider", key: "fontSize", label: "Font size", group: "content", min: 32, max: 120, step: 2 },
      { type: "slider", key: "letterSpacing", label: "Letter spacing", group: "content", min: -2, max: 12, step: 0.5 },
      { type: "slider", key: "lineHeight", label: "Line height", group: "content", min: 0.85, max: 1.4, step: 0.05 },
      {
        type: "select",
        key: "textAlign",
        label: "Text alignment",
        group: "content",
        options: [
          { value: "left", label: "Left" },
          { value: "center", label: "Center" },
          { value: "right", label: "Right" },
        ],
      },
      { type: "color", key: "background", label: "Preview background", group: "style" },
      { type: "slider", key: "cellSize", label: "Pixel cell size", group: "style", min: 3, max: 14, step: 1 },
      { type: "slider", key: "gridPadding", label: "Grid padding", group: "style", min: 0, max: 6, step: 1 },
      { type: "slider", key: "coverageThreshold", label: "Cell coverage threshold", group: "style", min: 0.05, max: 0.45, step: 0.01 },
      { type: "slider", key: "spawnSafetyMargin", label: "Spawn safety margin", group: "motion", min: 0, max: 8, step: 1 },
      { type: "switch", key: "debugOverlay", label: "Debug overlay", group: "export" },
      { type: "slider", key: "pieceSizePreference", label: "Piece-size preference", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "tetrominoFrequency", label: "Tetromino frequency", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "triominoFrequency", label: "Triomino frequency", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "shapeVariety", label: "Shape variety", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "pieceSpacing", label: "Piece spacing (fall)", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "spawnHeightMin", label: "Spawn height min", group: "motion", min: 0.5, max: 3, step: 0.1 },
      { type: "slider", key: "spawnHeightMax", label: "Spawn height max", group: "motion", min: 1, max: 4, step: 0.1 },
      { type: "slider", key: "landingDensity", label: "Landing density", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "edgeDetail", label: "Edge-detail quality", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "fallDuration", label: "Fall duration (ms)", group: "timing", min: 600, max: 4000, step: 50 },
      { type: "slider", key: "stagger", label: "Stagger (ms)", group: "timing", min: 0, max: 200, step: 5 },
      { type: "slider", key: "staggerRandomness", label: "Stagger randomness", group: "timing", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "horizontalMovement", label: "Horizontal movement", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "horizontalCorrections", label: "Horizontal corrections", group: "motion", min: 0, max: 5, step: 1 },
      { type: "slider", key: "rotationAmount", label: "Rotation amount", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "maxQuarterTurns", label: "Max quarter turns", group: "motion", min: 0, max: 3, step: 1 },
      { type: "slider", key: "rotationSpeed", label: "Rotation speed", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "landingBounce", label: "Landing bounce", group: "motion", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "landingDelay", label: "Landing delay (ms)", group: "timing", min: 0, max: 1000, step: 25 },
      { type: "slider", key: "finalHoldDuration", label: "Final hold (ms)", group: "timing", min: 0, max: 3000, step: 50 },
      { type: "slider", key: "revealOutSpeed", label: "Reveal-out speed", group: "timing", min: 0.35, max: 2, step: 0.05 },
      {
        type: "select",
        key: "revealOutDirection",
        label: "Reveal-out direction",
        group: "motion",
        options: [
          { value: "fall-down", label: "Fall down" },
          { value: "lift-up", label: "Lift up" },
          { value: "scatter-vertical", label: "Scatter vertically" },
          { value: "reverse-assembly", label: "Reverse assembly" },
        ],
      },
      {
        type: "select",
        key: "colorMode",
        label: "Color mode",
        group: "style",
        options: [
          { value: "solid", label: "Solid" },
          { value: "rainbow", label: "Rainbow by piece" },
          { value: "animated-rainbow", label: "Animated rainbow" },
          { value: "gradient", label: "Position gradient" },
        ],
      },
      { type: "color", key: "color", label: "Solid color", group: "style" },
      { type: "slider", key: "rainbowSaturation", label: "Rainbow saturation", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "rainbowBrightness", label: "Rainbow brightness", group: "style", min: 0.2, max: 1, step: 0.05 },
      { type: "slider", key: "rainbowSpread", label: "Rainbow spread", group: "style", min: 0.2, max: 2, step: 0.05 },
      { type: "slider", key: "hueSpeed", label: "Hue animation speed", group: "style", min: 0, max: 0.5, step: 0.01 },
      {
        type: "select",
        key: "gradientAxis",
        label: "Gradient axis",
        group: "style",
        options: [
          { value: "horizontal", label: "Horizontal" },
          { value: "vertical", label: "Vertical" },
        ],
      },
      { type: "slider", key: "glowIntensity", label: "Landing glow intensity", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "glowRadius", label: "Glow radius", group: "style", min: 1, max: 8, step: 0.5 },
      { type: "slider", key: "glowDuration", label: "Glow duration (ms)", group: "timing", min: 80, max: 800, step: 20 },
      { type: "slider", key: "impactFlash", label: "Impact flash", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "finalWordGlow", label: "Final-word glow", group: "style", min: 0, max: 1, step: 0.05 },
      { type: "slider", key: "layoutSeed", label: "Layout seed", group: "export", min: 1, max: 999999, step: 1 },
      { type: "slider", key: "motionSeed", label: "Motion seed", group: "export", min: 1, max: 999999, step: 1 },
      { type: "switch", key: "loop", label: "Loop", group: "timing" },
      { type: "switch", key: "autoPlay", label: "Auto play", group: "timing" },
    ],
    supportsOutAnimation: true,
    exportNotes:
      "Canvas 2D only — no animation libraries. Export includes a self-contained component with layoutSeed and motionSeed.",
    component: TetrisPixelText as AnimationDefinition["component"],
  },
];

export function getAnimationById(id: string): AnimationDefinition | undefined {
  return animationRegistry.find((entry) => entry.id === id);
}

export function getDefaultSettings(definition: AnimationDefinition): AnimationSettings {
  return { ...definition.defaultSettings };
}
