import type { TransitionDefinition, TransitionId } from "./types";
import {
  curtainEdgeOptions,
  curtainOriginOptions,
  defaultCurtainLook,
  defaultPixelLook,
} from "./types";

const sharedControls = [
  {
    key: "duration" as const,
    label: "Duration",
    min: 240,
    max: 1200,
    step: 20,
    suffix: "ms",
  },
  {
    key: "intensity" as const,
    label: "Intensity",
    min: 0,
    max: 100,
    step: 2,
  },
  {
    key: "stagger" as const,
    label: "Stagger",
    min: 0,
    max: 220,
    step: 10,
    suffix: "ms",
  },
  {
    key: "radius" as const,
    label: "Radius",
    min: 0,
    max: 120,
    step: 2,
    suffix: "px",
  },
];

const sharedDefaults = {
  ...defaultCurtainLook,
  ...defaultPixelLook,
};

export const transitionDefinitions: TransitionDefinition[] = [
  {
    id: "editorial-wipe",
    title: "Editorial Wipe",
    eyebrow: "Landing → Article",
    engine: "css",
    dependencies: ["React", "CSS custom properties"],
    defaults: {
      ...sharedDefaults,
      duration: 560,
      intensity: 72,
      stagger: 80,
      radius: 8,
      curtains: 6,
    },
    controls: sharedControls,
  },
  {
    id: "product-shelf-slide",
    title: "Product Shelf Slide",
    eyebrow: "Section → Section",
    engine: "css",
    dependencies: ["React", "CSS custom properties"],
    defaults: {
      ...sharedDefaults,
      duration: 460,
      intensity: 52,
      stagger: 40,
      radius: 12,
      curtains: 6,
    },
    controls: sharedControls,
  },
  {
    id: "spotlight-iris",
    title: "Spotlight Iris",
    eyebrow: "Home → Feature",
    engine: "css",
    dependencies: ["React", "CSS clip-path"],
    defaults: {
      ...sharedDefaults,
      duration: 620,
      intensity: 76,
      stagger: 60,
      radius: 100,
      curtains: 6,
    },
    controls: sharedControls,
  },
  {
    id: "receipt-lift",
    title: "Receipt Lift",
    eyebrow: "Index → Story",
    engine: "css",
    dependencies: ["React", "CSS custom properties"],
    defaults: {
      ...sharedDefaults,
      duration: 520,
      intensity: 64,
      stagger: 30,
      radius: 22,
      curtains: 6,
    },
    controls: sharedControls,
  },
  {
    id: "soft-crossfade-blur",
    title: "Soft Crossfade Blur",
    eyebrow: "Page → Page",
    engine: "css",
    dependencies: ["React", "CSS filter"],
    defaults: {
      ...sharedDefaults,
      duration: 320,
      intensity: 28,
      stagger: 0,
      radius: 10,
      curtains: 6,
    },
    controls: sharedControls,
  },
  {
    id: "curtain-fall",
    title: "Curtain Fall",
    eyebrow: "Landing → Article",
    engine: "three",
    dependencies: ["React", "three", "WebGL"],
    defaults: {
      ...sharedDefaults,
      duration: 900,
      intensity: 70,
      stagger: 70,
      radius: 0,
      curtains: 8,
      curtainColorA: "#071018",
      curtainColorB: "#10a4ff",
      curtainGradient: "vertical",
      curtainFallIn: "left",
      curtainFallOut: "left",
      curtainEdge: "flat",
    },
    controls: [
      {
        key: "curtains",
        label: "Curtains",
        min: 3,
        max: 16,
        step: 1,
      },
      {
        key: "duration",
        label: "Duration",
        min: 400,
        max: 1600,
        step: 20,
        suffix: "ms",
      },
      {
        key: "stagger",
        label: "Stagger",
        min: 20,
        max: 180,
        step: 5,
        suffix: "ms",
      },
      {
        key: "intensity",
        label: "Drop depth",
        min: 20,
        max: 100,
        step: 2,
      },
      {
        type: "color",
        key: "curtainColorA",
        label: "Color A",
      },
      {
        type: "color",
        key: "curtainColorB",
        label: "Color B",
      },
      {
        type: "select",
        key: "curtainGradient",
        label: "Fill",
        options: [
          { value: "solid", label: "Solid (A)" },
          { value: "vertical", label: "Vertical gradient" },
          { value: "horizontal", label: "Horizontal gradient" },
        ],
      },
      {
        type: "select",
        key: "curtainFallIn",
        label: "Fall in from",
        options: curtainOriginOptions,
      },
      {
        type: "select",
        key: "curtainFallOut",
        label: "Fall out from",
        options: curtainOriginOptions,
      },
      {
        type: "select",
        key: "curtainEdge",
        label: "Edge shape",
        options: curtainEdgeOptions,
      },
    ],
  },
  {
    id: "pixel-wormhole",
    title: "Pixel Wormhole",
    eyebrow: "Landing → Article",
    engine: "three",
    dependencies: ["React", "three", "WebGL"],
    defaults: {
      ...sharedDefaults,
      duration: 1100,
      intensity: 72,
      stagger: 90,
      radius: 0,
      curtains: 6,
      pixelDensity: 28,
      pixelColorMode: "preserve",
      pixelColorA: "#10a4ff",
      pixelColorB: "#ffffff",
    },
    controls: [
      {
        key: "duration",
        label: "Duration",
        min: 600,
        max: 1800,
        step: 20,
        suffix: "ms",
      },
      {
        key: "pixelDensity",
        label: "Pixel density",
        min: 14,
        max: 42,
        step: 1,
      },
      {
        key: "stagger",
        label: "Corner stagger",
        min: 0,
        max: 200,
        step: 5,
        suffix: "ms",
      },
      {
        key: "intensity",
        label: "Warp depth",
        min: 20,
        max: 100,
        step: 2,
      },
      {
        type: "select",
        key: "pixelColorMode",
        label: "Pixel color",
        options: [
          { value: "preserve", label: "Keep page colors" },
          { value: "solid", label: "Solid (A)" },
          { value: "gradient", label: "Gradient A → B" },
          { value: "white", label: "White glow" },
        ],
      },
      {
        type: "color",
        key: "pixelColorA",
        label: "Color A",
      },
      {
        type: "color",
        key: "pixelColorB",
        label: "Color B",
      },
    ],
  },
];

export function getTransitionDefinition(id: TransitionId) {
  return transitionDefinitions.find((transition) => transition.id === id);
}
