import {
  DEFAULT_TETRIS_SETTINGS,
  type TetrisPixelSettings,
} from "./types";

export type PresetId =
  | "classic-blocks"
  | "arcade-rainbow"
  | "slow-assembly"
  | "glitch-build"
  | "minimal-lock-in"
  | "high-definition"
  | "fast-build";

export type PresetDefinition = {
  id: PresetId;
  label: string;
  description: string;
  settings: Partial<TetrisPixelSettings>;
};

export const TETRIS_PRESETS: PresetDefinition[] = [
  {
    id: "classic-blocks",
    label: "Classic Blocks",
    description: "High density, white pieces, ~4s reveal, subtle glow.",
    settings: {
      ...DEFAULT_TETRIS_SETTINGS,
      textDensity: "high",
      renderQuality: "high",
      edgeDetailLevel: "detailed",
      pieceScale: "mixed",
      animationDuration: 4,
      concurrency: "auto",
      colorMode: "solid",
      color: "#ffffff",
      background: "#000000",
      cellSize: 0,
      horizontalMovement: 0.65,
      rotationAmount: 0.7,
      maxQuarterTurns: 2,
      fallDuration: 1800,
      stagger: 45,
      glowIntensity: 0.45,
      impactFlash: 0.4,
      landingBounce: 0.35,
    },
  },
  {
    id: "high-definition",
    label: "High Definition",
    description: "Ultra-dense typography, high render quality, crisp 4s build.",
    settings: {
      textDensity: "ultra",
      renderQuality: "high",
      edgeDetailLevel: "detailed",
      pieceScale: "mixed",
      animationDuration: 4,
      concurrency: "balanced",
      fontSize: 160,
      colorMode: "solid",
      color: "#ffffff",
      background: "#000000",
      glowIntensity: 0.28,
      glowRadius: 2,
      impactFlash: 0.25,
      finalWordGlow: 0.35,
      horizontalMovement: 0.45,
      rotationAmount: 0.55,
      maxQuarterTurns: 2,
      fallDuration: 1600,
      stagger: 28,
    },
  },
  {
    id: "fast-build",
    label: "Fast Build",
    description: "High density in ~1.8s with high concurrency — smooth, not sped-up.",
    settings: {
      textDensity: "high",
      renderQuality: "balanced",
      edgeDetailLevel: "detailed",
      pieceScale: "mixed",
      animationDuration: 1.8,
      concurrency: "high",
      fontSize: 120,
      colorMode: "solid",
      color: "#ffffff",
      background: "#000000",
      horizontalMovement: 0.35,
      horizontalCorrections: 1,
      rotationAmount: 0.35,
      maxQuarterTurns: 1,
      fallDuration: 1100,
      stagger: 18,
      glowIntensity: 0.35,
      glowDuration: 160,
      impactFlash: 0.3,
      landingBounce: 0.22,
    },
  },
  {
    id: "arcade-rainbow",
    label: "Arcade Rainbow",
    description: "Rainbow by piece, stronger movement, brighter impact.",
    settings: {
      textDensity: "high",
      renderQuality: "high",
      pieceScale: "mixed",
      animationDuration: 3.2,
      concurrency: "high",
      colorMode: "rainbow",
      color: "#ffffff",
      background: "#000000",
      horizontalMovement: 0.9,
      horizontalCorrections: 3,
      rotationAmount: 0.85,
      maxQuarterTurns: 3,
      fallDuration: 1400,
      stagger: 38,
      staggerRandomness: 0.5,
      glowIntensity: 0.65,
      impactFlash: 0.7,
      glowRadius: 4,
      rainbowSaturation: 0.9,
      rainbowBrightness: 0.95,
      rainbowSpread: 1,
    },
  },
  {
    id: "slow-assembly",
    label: "Slow Assembly",
    description: "Longer reveal, larger pieces, visible rotations.",
    settings: {
      textDensity: "high",
      renderQuality: "high",
      pieceScale: "large",
      animationDuration: 8,
      concurrency: "low",
      colorMode: "solid",
      color: "#ffffff",
      background: "#000000",
      pieceSizePreference: 0.9,
      tetrominoFrequency: 0.85,
      fallDuration: 2800,
      stagger: 90,
      staggerRandomness: 0.15,
      horizontalMovement: 0.55,
      rotationAmount: 0.9,
      maxQuarterTurns: 2,
      glowIntensity: 0.55,
      glowDuration: 520,
      landingBounce: 0.4,
    },
  },
  {
    id: "glitch-build",
    label: "Glitch Build",
    description: "Fast corrections, more rotations, short flashes.",
    settings: {
      textDensity: "detailed",
      renderQuality: "balanced",
      pieceScale: "small",
      animationDuration: 2.2,
      concurrency: "maximum",
      colorMode: "animated-rainbow",
      color: "#ffffff",
      background: "#050508",
      fallDuration: 1100,
      stagger: 28,
      staggerRandomness: 0.75,
      horizontalMovement: 1,
      horizontalCorrections: 4,
      rotationAmount: 1,
      maxQuarterTurns: 3,
      rotationSpeed: 0.9,
      glowIntensity: 0.5,
      impactFlash: 0.95,
      glowDuration: 180,
      hueSpeed: 0.22,
      rainbowSpread: 1.2,
    },
  },
  {
    id: "minimal-lock-in",
    label: "Minimal Lock-In",
    description: "Almost no lateral move, few rotations, restrained glow.",
    settings: {
      textDensity: "high",
      renderQuality: "high",
      pieceScale: "mixed",
      animationDuration: 3.5,
      concurrency: "balanced",
      colorMode: "solid",
      color: "#ffffff",
      background: "#000000",
      horizontalMovement: 0.08,
      horizontalCorrections: 1,
      rotationAmount: 0.15,
      maxQuarterTurns: 1,
      fallDuration: 1600,
      stagger: 40,
      glowIntensity: 0.22,
      impactFlash: 0.15,
      landingBounce: 0.12,
      finalWordGlow: 0.25,
    },
  },
];

export function applyPreset(
  presetId: PresetId,
  current: TetrisPixelSettings,
): TetrisPixelSettings {
  const preset = TETRIS_PRESETS.find((p) => p.id === presetId);
  if (!preset) return current;
  return {
    ...current,
    ...preset.settings,
    layoutSeed: current.layoutSeed,
    motionSeed: current.motionSeed,
    phase: current.phase,
    paused: false,
    line2: current.line2,
  };
}
